version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ninechars
      MYSQL_DATABASE: tuc
      MYSQL_USER: lybe
      MYSQL_PASSWORD: ninechars
    volumes:
      - ./dump/:/docker-entrypoint-initdb.d
    ports:
      - "9906:3306"
  web:
    build: .
    container_name: php-apache
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
